name             '.'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures .'
long_description 'Installs/Configures .'
version          '0.1.0'
